//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCultureWave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int idMessage { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public int idUser { get; set; }
    
        public virtual user user { get; set; }
    }
}
