//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCultureWave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class space
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public space()
        {
            this.eventTable = new HashSet<eventTable>();
            this.seat = new HashSet<seat>();
        }
    
        public int idSpace { get; set; }
        public string name { get; set; }
        public int capacity { get; set; }
        public Nullable<bool> fixeSeats { get; set; }
        public Nullable<bool> available { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eventTable> eventTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<seat> seat { get; set; }
    }
}
