//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiCultureWave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int idTicket { get; set; }
        public int idReserve { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public string description { get; set; }
        public System.DateTime creationDate { get; set; }
    
        public virtual reserve reserve { get; set; }
    }
}
